[package]
name                  = "veryl-parser"
version               = "0.1.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parol_runtime = {version = "0.9.0", features = ["auto_generation"]}
regex         = "1.7.0"
thiserror     = {workspace = true}

[build-dependencies]
parol   = "0.15.0"
walkdir = "2.3.2"
