[package]
name = "veryl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap            = {version = "4.0.29", features = ["derive"]}
console         = "0.15.2"
env_logger      = "0.10.0"
miette          = {version = "5.5.0", features = ["fancy"]}
similar         = {version = "2.2.1", features = ["text", "inline"]}
thiserror       = "1.0"
veryl-emitter   = {version = "0.1.0", path = "../emitter"}
veryl-parser    = {version = "0.1.0", path = "../parser"}
veryl-formatter = {version = "0.1.0", path = "../formatter"}
walkdir         = "2.3.2"
